#!/usr/bin/env bash
# SPDX-License-Identifier: MIT
#
# MIT License
#
# Copyright (c) 2019 Ericsson
#
# Permission is hereby granted, free of charge, to any person obtaining a copy
# of this software and associated documentation files (the "Software"), to deal
# in the Software without restriction, including without limitation the rights
# to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
# copies of the Software, and to permit persons to whom the Software is furnished
# to do so, subject to the following conditions:
#
# The above copyright notice and this permission notice (including the next
# paragraph) shall be included in all copies or substantial portions of the
# Software.
#
# THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
# IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY, FITNESS
# FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE AUTHORS
# OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER LIABILITY,
# WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM, OUT OF
# OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE SOFTWARE.

set -e

if [ "$#" -lt 2 ] || [ "$#" -gt 3 ]; then
	cat << EOF
USAGE
	setup <path> <url> [<rev>]

	path = workspace path
	url  = OWEL url
	rev  = a specific revision (SHA-1/TAG)

EXAMPLES
	# setup 'xyz-top' in directory 'xyz'
	$ setup xyz ssh://xyz/xyz-top

	# setup 'xyz-top' starting from 1.0.1
	$ setup src/xyz-1.0.1 ssh://xyz/xyz-top 1.0.1
EOF
	exit 1
fi

path="$1"
url="$2"

if [ -d "${path}" ]; then
	echo "error: '${path}' already exist"
	exit 1
fi

if ! command -v git > /dev/null; then
	echo "error: 'git' is not found"
	exit 2
fi

mkdir -vp "${path}"
cd "${path}"

if ! git clone "${url}"; then
	echo "error: 'git clone ${url}' failed"
	exit 3
fi

ove_url="https://github.com/Ericsson/ove.git"
if ! git clone ${ove_url} .ove; then
	echo "error: 'git clone ${ove_url} .ove' failed"
	exit 4
fi

owel=${2##*/}
owel=${owel%.*}
ln -s "${owel}" .owel
ln -s .ove/ove ove

if [ "$#" -eq 3 ]; then
	git -C .owel -c advice.detachedHead=false checkout "$3" || :
fi

echo
echo "Please run: "
echo "$ cd ${path}"
echo "$ source ove"
