#!/usr/bin/env bash
# SPDX-License-Identifier: MIT
#
# MIT License
#
# Copyright (c) 2023 Ericsson
#
# Permission is hereby granted, free of charge, to any person obtaining a copy
# of this software and associated documentation files (the "Software"), to deal
# in the Software without restriction, including without limitation the rights
# to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
# copies of the Software, and to permit persons to whom the Software is furnished
# to do so, subject to the following conditions:
#
# The above copyright notice and this permission notice (including the next
# paragraph) shall be included in all copies or substantial portions of the
# Software.
#
# THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
# IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY, FITNESS
# FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE AUTHORS
# OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER LIABILITY,
# WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM, OUT OF
# OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE SOFTWARE.

set -e

function supported {
	if [ "${OVE_OS_ID}" = "" ]; then
		echo "error: OVE is not initialized" 1>&2
		return 1
	elif [ "${OVE_OS_ID}" = "ubuntu" ]; then
		case "${OVE_OS_VER:?}" in
			20.04|22.04|24.04)
				return 0
				;;
		esac
	elif [ "${OVE_OS_ID}" = "debian" ]; then
		case "${OVE_OS_VER:?}" in
			11|12)
				return 0
				;;
		esac
	fi

	echo "error: ${OVE_OS:?} ${OVE_OS_VER} is not yet supported" 1>&2
	return 1
}

function pre {
	local c
	local deps

	if command -v incus > /dev/null; then
		exit 0
	elif [ "$EUID" -ne 0 ]; then
		prefix="sudo"
	fi

	if ${prefix} sh -c "[ -e /proc/1/environ ]" && \
		${prefix} sh -c "tr '\0' '\n' < /proc/1/environ | grep -q 'container='"; then
		# inside container => skip
		exit 0
	elif ! supported; then
		exit 0
	fi

	deps+=" curl"
	deps+=" dpkg"
	deps+=" gpg"
	deps+=" sg"
	for c in ${deps}; do
		if ! command -v "${c}" > /dev/null; then
			echo "error: command '${c}' is missing" 1>&2
			exit 1
		fi
	done

	deps=" adduser"
	deps+=" usermod"
	for c in ${deps}; do
		if ! ${prefix} bash -c "command -v ${c}" > /dev/null; then
			echo "error: command '${c}' is missing" 1>&2
			exit 1
		fi
	done
}

function verify {
	if [ ! -s "${OVE_TMP:?}/incus-key.asc" ]; then
		curl -fsSL https://pkgs.zabbly.com/key.asc > "${OVE_TMP:?}/incus-key.asc"
	elif ! gpg --show-keys --fingerprint "${OVE_TMP:?}/incus-key.asc" 2> /dev/null | \
		grep -q "4EFC 5906 96CB 15B8 7C73  A3AD 82CC 8797 C838 DCFD"; then
		rm "${OVE_TMP:?}/incus-key.asc"
		echo "fatal: gpg key mismatch! Key '${OVE_TMP:?}/incus-key.asc' removed" 1>&2
		exit 1
	fi
}

function key {
	${prefix} mkdir \
		-p \
		-v \
		/etc/apt/keyrings
	${prefix} bash \
		-c \
		"cp -a ${OVE_TMP:?}/incus-key.asc /etc/apt/keyrings/zabbly.asc"
}

function sources {
	# shellcheck disable=SC2016
	${prefix} sh -c 'cat <<EOF > /etc/apt/sources.list.d/zabbly-incus-stable.sources
Enabled: yes
Types: deb
URIs: https://pkgs.zabbly.com/incus/stable
Suites: $(. /etc/os-release && echo ${VERSION_CODENAME})
Components: main
Architectures: $(dpkg --print-architecture)
Signed-By: /etc/apt/keyrings/zabbly.asc

EOF'
}

function install {
	export DEBIAN_FRONTEND=noninteractive
	${prefix} \
		apt-get \
		-qq \
		update
	${prefix} \
		apt-get \
		-qq \
		-y \
		-o=Dpkg::Progress=0 \
		-o=Dpkg::Progress-Fancy=false \
		install \
		incus
	incus --version
	${prefix} adduser --quiet "${OVE_USER:?}" incus-admin
}

function init {
	local ret

	ret=0

	set +x
	set +e
	read \
		-p "minimal incus installation? (this dialog will timeout in 30 seconds) (Y/n) " \
		-r \
		-t 30
	ret=$?
	set -x
	if [ "${REPLY,}" = "y" ] || [ "${ret}" -gt 128 ]; then
		suffix="--minimal"
	fi
	sg incus-admin -c "incus admin init ${suffix}"
	${prefix} usermod -aG incus-admin "${OVE_USER:?}"
	if ! sg incus-admin -c "incus list" > /dev/null; then
		echo "error: not possible to run 'incus list'" 1>&2
		exit 1
	fi
	set +x

	echo "---"
	echo "incus is now installed. To proceed, you have two options:"
	echo
	echo "a) logout and login"
	echo "b) exec sg incus-admin \"newgrp \$(id -gn)\""
	echo
	echo "After a or b, enjoy incus!"
	echo "---"
	exit 42
}

pre
set -x
verify
key
sources
install
if [[ "$*" == *--no-init* ]]; then
	exit 0
fi
init
