#!/usr/bin/env bash
# SPDX-License-Identifier: MIT
#
# MIT License
#
# Copyright (c) 2020 Ericsson
#
# Permission is hereby granted, free of charge, to any person obtaining a copy
# of this software and associated documentation files (the "Software"), to deal
# in the Software without restriction, including without limitation the rights
# to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
# copies of the Software, and to permit persons to whom the Software is furnished
# to do so, subject to the following conditions:
#
# The above copyright notice and this permission notice (including the next
# paragraph) shall be included in all copies or substantial portions of the
# Software.
#
# THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
# IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY, FITNESS
# FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE AUTHORS
# OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER LIABILITY,
# WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM, OUT OF
# OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE SOFTWARE.

if [ -z "${TMUX+x}" ]; then
	echo "error: only available for TMUX sessions for now"
	exit 1
fi

$OVE_INIT_STRING

# news
ove-loop 3600 0 0 "news"
sleep 1

# ahead
ove-loop 0 1 0 "ahead"
while true; do
	for file in "${OVE_PROJECT_TMP_DIR}"/inotifywait-ahead-*.uniq; do
		[ -s "${file}" ] && break 2
	done
	sleep 0.1
done

# fetch
ove-loop 3600 0 0 "fetch"

# task: duckduckgo.com/?q=taskwarrior
if command -v task > /dev/null; then
	ove-loop 0 1 0 "do . task"
fi
