#!/usr/bin/env bash
# SPDX-License-Identifier: MIT
#
# MIT License
#
# Copyright (c) 2019 Ericsson
#
# Permission is hereby granted, free of charge, to any person obtaining a copy
# of this software and associated documentation files (the "Software"), to deal
# in the Software without restriction, including without limitation the rights
# to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
# copies of the Software, and to permit persons to whom the Software is furnished
# to do so, subject to the following conditions:
#
# The above copyright notice and this permission notice (including the next
# paragraph) shall be included in all copies or substantial portions of the
# Software.
#
# THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
# IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY, FITNESS
# FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE AUTHORS
# OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER LIABILITY,
# WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM, OUT OF
# OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE SOFTWARE.

$OVE_INIT_STRING

# list all MAJOR.MINOR.PATCH tags
ove-tag | grep -o '[0-9]\+\.[0-9]\+\.[0-9]\+' | sort -Vr > $OVE_TMP/tags

if ! [ -s $OVE_TMP/tags ]; then
	echo "error: no tags"
	exit 1
fi

# start tag
s=$(head -1 $OVE_TMP/tags)

# create a CHANGELOG
for t in $(tail -n +2 $OVE_TMP/tags); do
	echo $s
	ove-log-project $t $s;
	s=$t
done > $OVE_PROJECT_DIR/CHANGELOG

# remove color codes
sed -i \
	-r \
	-e "s/\x1b\[1;3[1,3]m//g" \
	-e "s/\x1b\[[0-9]+m//g" \
	-e "s/\x1b\[m//g" $OVE_PROJECT_DIR/CHANGELOG
